import { describe, expect, it, vi } from "vitest";

import {
  createFailureResult,
  createNotAvailableResult,
  createSuccessResult
} from "../../src/contracts/tool-result.js";
import { InvalidInputError, NotAvailableError } from "../../src/lib/mcp-errors.js";
import { createServer } from "../../src/server/create-server.js";

type RegisteredTool = {
  annotations?: Record<string, unknown>;
  description?: string;
  handler: (args: Record<string, unknown>) => Promise<unknown>;
};

describe("get_transcript tool", () => {
  it("registers a read-only transcript tool that can use an injected youtube service", async () => {
    const youtubeService = {
      getTranscript: vi.fn().mockResolvedValue({
        kind: "transcript",
        videoId: "dQw4w9WgXcQ",
        canonicalUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        source: "watch",
        title: "Build an MCP Server",
        channelTitle: "Example Dev",
        language: "English",
        includeTimestamps: true,
        retrievalMethod: "fallback",
        languages: [
          {
            label: "English",
            languageCode: "en",
            isSelected: true,
            isAutoGenerated: true,
            isTranslatable: true
          },
          {
            label: "Deutsch",
            languageCode: "de",
            isSelected: false,
            isTranslatable: true
          }
        ],
        segmentCount: 2,
        text: "0:00 Hello world\n0:01 Build with MCP",
        segments: [
          {
            startMs: 0,
            endMs: 1200,
            startTimeSeconds: 0,
            endTimeSeconds: 1,
            startTimeText: "0:00",
            text: "Hello world"
          },
          {
            startMs: 1200,
            endMs: 4800,
            startTimeSeconds: 1,
            endTimeSeconds: 4,
            startTimeText: "0:01",
            text: "Build with MCP"
          }
        ]
      })
    };
    const server = createServer({ youtubeService });
    const tool = (
      server as unknown as { _registeredTools: Record<string, RegisteredTool> }
    )._registeredTools.get_transcript;

    expect(tool).toBeDefined();
    expect(tool.description).toContain("Fetch a public YouTube transcript");
    expect(tool.annotations).toEqual({ readOnlyHint: true });
    await expect(
      tool.handler({
        video: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        language: "de",
        includeTimestamps: true
      })
    ).resolves.toEqual(
      createSuccessResult({
        summary:
          'Loaded public transcript for "Build an MCP Server" in English. Fallback extractor used.',
        data: {
          id: "dQw4w9WgXcQ",
          canonicalUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
          title: "Build an MCP Server",
          channelTitle: "Example Dev",
          language: "English",
          includeTimestamps: true,
          retrievalMethod: "fallback",
          languages: [
            {
              label: "English",
              languageCode: "en",
              isSelected: true,
              isAutoGenerated: true,
              isTranslatable: true
            },
            {
              label: "Deutsch",
              languageCode: "de",
              isSelected: false,
              isTranslatable: true
            }
          ],
          segmentCount: 2,
          text: "0:00 Hello world\n0:01 Build with MCP",
          segments: [
            {
              startTimeText: "0:00",
              startTimeSeconds: 0,
              endTimeSeconds: 1,
              text: "Hello world"
            },
            {
              startTimeText: "0:01",
              startTimeSeconds: 1,
              endTimeSeconds: 4,
              text: "Build with MCP"
            }
          ]
        }
      })
    );
    expect(youtubeService.getTranscript).toHaveBeenCalledWith(
      "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
      {
        language: "de",
        includeTimestamps: true
      }
    );
  });

  it("returns actionable invalid-input failures for malformed transcript requests", async () => {
    const server = createServer({
      youtubeService: {
        getTranscript: vi.fn()
      }
    });
    const tool = (
      server as unknown as { _registeredTools: Record<string, RegisteredTool> }
    )._registeredTools.get_transcript;

    await expect(tool.handler({})).resolves.toEqual(
      createFailureResult(
        new InvalidInputError(
          "Provide a YouTube video URL or bare 11-character video ID in `video`."
        )
      )
    );
    await expect(tool.handler({ video: "   " })).resolves.toEqual(
      createFailureResult(
        new InvalidInputError(
          "Provide a YouTube video URL or bare 11-character video ID in `video`."
        )
      )
    );
    await expect(
      tool.handler({
        video: "dQw4w9WgXcQ",
        language: "   "
      })
    ).resolves.toEqual(
      createFailureResult(
        new InvalidInputError(
          "Provide a non-empty `language` string when requesting a transcript language."
        )
      )
    );
    await expect(
      tool.handler({
        video: "dQw4w9WgXcQ",
        includeTimestamps: "yes"
      })
    ).resolves.toEqual(
      createFailureResult(
        new InvalidInputError(
          "Provide `includeTimestamps` as `true` or `false` when formatting transcript text."
        )
      )
    );
  });

  it("keeps the transcript payload compact and omits internal normalization fields", async () => {
    const server = createServer({
      youtubeService: {
        getTranscript: vi.fn().mockResolvedValue({
          kind: "transcript",
          videoId: "dQw4w9WgXcQ",
          canonicalUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
          source: "id",
          language: "English",
          includeTimestamps: false,
          retrievalMethod: "primary",
          languages: [
            {
              label: "English",
              isSelected: true
            }
          ],
          segmentCount: 1,
          text: "Hello world",
          segments: [
            {
              startMs: 0,
              endMs: 1200,
              startTimeSeconds: 0,
              endTimeSeconds: 1,
              startTimeText: "0:00",
              text: "Hello world"
            }
          ]
        })
      }
    });
    const tool = (
      server as unknown as { _registeredTools: Record<string, RegisteredTool> }
    )._registeredTools.get_transcript;
    const result = (await tool.handler({
      video: "dQw4w9WgXcQ"
    })) as {
      structuredContent: {
        status: string;
        data: Record<string, unknown>;
      };
    };

    expect(result.structuredContent.status).toBe("ok");
    expect(result.structuredContent.data).toMatchObject({
      id: "dQw4w9WgXcQ",
      language: "English",
      includeTimestamps: false,
      retrievalMethod: "primary",
      segmentCount: 1,
      text: "Hello world",
      segments: [
        {
          startTimeText: "0:00",
          startTimeSeconds: 0,
          endTimeSeconds: 1,
          text: "Hello world"
        }
      ]
    });
    expect(result.structuredContent.data).not.toHaveProperty("videoId");
    expect(result.structuredContent.data).not.toHaveProperty("source");
    expect(result.structuredContent.data).not.toHaveProperty("startMs");
    expect(result.structuredContent.data).not.toHaveProperty("endMs");
  });

  it("surfaces transcript-unavailable results cleanly after fallback recovery is exhausted", async () => {
    const server = createServer({
      youtubeService: {
        getTranscript: vi.fn().mockRejectedValue(
          new NotAvailableError("No public transcript is available for this video.", {
            cause: "transcript_unavailable",
            details: {
              videoId: "dQw4w9WgXcQ",
              fallback: true
            }
          })
        )
      }
    });
    const tool = (
      server as unknown as { _registeredTools: Record<string, RegisteredTool> }
    )._registeredTools.get_transcript;

    await expect(
      tool.handler({
        video: "dQw4w9WgXcQ"
      })
    ).resolves.toEqual(
      createNotAvailableResult({
        summary: "No public transcript is available for this video.",
        reason: "transcript_unavailable",
        data: {
          videoId: "dQw4w9WgXcQ",
          fallback: true
        }
      })
    );
  });
});
