import type {
  ParsedYouTubeReference,
  YouTubeChannelReference,
  YouTubePlaylistReference,
  YouTubeVideoReference
} from "./reference.js";

export type YouTubeLookupReference = ParsedYouTubeReference;

export type YouTubeVideoLookup = YouTubeVideoReference;

export type YouTubePlaylistLookup = YouTubePlaylistReference;

export type YouTubeChannelLookup = YouTubeChannelReference;

export type YouTubeLookupInput = string | YouTubeLookupReference;

export type YouTubeVideoInput = string | YouTubeVideoLookup;

export type YouTubePlaylistInput = string | YouTubePlaylistLookup;

export type YouTubeChannelInput = string | YouTubeChannelLookup;

export const DEFAULT_SEARCH_RESULTS = 5;
export const MAX_SEARCH_RESULTS = 10;
export const DEFAULT_PLAYLIST_RESULTS = 10;
export const MAX_PLAYLIST_RESULTS = 25;
export const DEFAULT_CHANNEL_RESULTS = 10;
export const MAX_CHANNEL_RESULTS = 30;
export const DEFAULT_COMMENT_RESULTS = 20;
export const MAX_COMMENT_RESULTS = 50;

export type YouTubeVideoChapter = {
  title: string;
  startTimeSeconds: number;
  thumbnailUrl?: string;
};

export type YouTubeVideoRecord = {
  kind: "video";
  id: string;
  canonicalUrl: string;
  source: YouTubeVideoLookup["source"];
  title?: string;
  description?: string;
  channelId?: string;
  channelTitle?: string;
  durationSeconds?: number;
  viewCount?: number;
  likeCount?: number;
  thumbnails: string[];
  keywords?: string[];
  category?: string;
  isFamilySafe?: boolean;
  isUnlisted?: boolean;
  isLive?: boolean;
  isUpcoming?: boolean;
  chapters?: YouTubeVideoChapter[];
  playlistId?: string;
  startTimeSeconds?: number;
};

export type YouTubePlaylistQuery =
  | {
      playlist: YouTubePlaylistInput;
      pageToken?: never;
      maxResults?: number;
    }
  | {
      pageToken: string;
      playlist?: never;
      maxResults?: number;
    };

export type YouTubePlaylistItem = {
  kind: "video";
  id: string;
  canonicalUrl: string;
  title: string;
  channelTitle?: string;
  durationText?: string;
  durationSeconds?: number;
  position?: number;
  thumbnails: string[];
  isPlayable: boolean;
  isLive: boolean;
  isUpcoming: boolean;
};

export type YouTubePlaylistRecord = {
  kind: "playlist";
  id: string;
  canonicalUrl: string;
  source: YouTubePlaylistLookup["source"];
  title?: string;
  description?: string;
  channelId?: string;
  channelTitle?: string;
  itemCountText?: string;
  privacy?: string;
  viewCountText?: string;
  lastUpdatedText?: string;
  thumbnails: string[];
  pageSize: number;
  nextPageToken?: string;
  items: YouTubePlaylistItem[];
};

export type YouTubeChannelVideoItem = {
  id: string;
  canonicalUrl: string;
  title: string;
  thumbnails: string[];
  publishedText?: string;
  durationText?: string;
  viewCountText?: string;
};

export type YouTubeChannelRecord = {
  kind: "channel";
  canonicalUrl: string;
  source: YouTubeChannelLookup["source"];
  id?: string;
  handle?: string;
  title?: string;
  description?: string;
  subscriberCountText?: string;
  videoCountText?: string;
  viewCountText?: string;
  thumbnails: string[];
  recentVideos?: YouTubeChannelVideoItem[];
};

export type YouTubeSearchUploadDate =
  | "all"
  | "hour"
  | "today"
  | "week"
  | "month"
  | "year";

export type YouTubeSearchDuration = "all" | "short" | "medium" | "long";

export type YouTubeSearchSortBy =
  | "relevance"
  | "rating"
  | "upload_date"
  | "view_count";

export type YouTubeSearchFeature =
  | "hd"
  | "subtitles"
  | "creative_commons"
  | "live"
  | "4k"
  | "hdr";

export type YouTubeSearchFilters = {
  uploadDate?: YouTubeSearchUploadDate;
  duration?: YouTubeSearchDuration;
  sortBy?: YouTubeSearchSortBy;
  features?: YouTubeSearchFeature[];
};

export type YouTubeSearchQuery =
  | {
      query: string;
      pageToken?: never;
      maxResults?: number;
      filters?: YouTubeSearchFilters;
    }
  | {
      pageToken: string;
      query?: never;
      maxResults?: number;
      filters?: never;
    };

export type YouTubeSearchResult = {
  kind: "video";
  id: string;
  canonicalUrl: string;
  title: string;
  channelId?: string;
  channelTitle?: string;
  publishedText?: string;
  viewCountText?: string;
  durationText?: string;
  durationSeconds?: number;
  snippet?: string;
  thumbnails: string[];
  isLive: boolean;
  isUpcoming: boolean;
};

export type YouTubeSearchPage = {
  query: string;
  pageSize: number;
  estimatedResults?: number;
  refinements?: string[];
  filters?: YouTubeSearchFilters;
  nextPageToken?: string;
  results: YouTubeSearchResult[];
};

export type YouTubeTranscriptSegment = {
  startMs: number;
  endMs: number;
  startTimeSeconds: number;
  endTimeSeconds: number;
  startTimeText: string;
  text: string;
};

export type YouTubeTranscriptLanguage = {
  label: string;
  languageCode?: string;
  isSelected: boolean;
  isAutoGenerated?: boolean;
  isTranslatable?: boolean;
};

export type YouTubeTranscriptRetrievalMethod = "primary" | "fallback";

export type YouTubeTranscriptRecord = {
  kind: "transcript";
  videoId: string;
  canonicalUrl: string;
  source: YouTubeVideoLookup["source"];
  title?: string;
  channelTitle?: string;
  language: string;
  languages: YouTubeTranscriptLanguage[];
  includeTimestamps: boolean;
  retrievalMethod: YouTubeTranscriptRetrievalMethod;
  segmentCount: number;
  segments: YouTubeTranscriptSegment[];
  text: string;
};

export type YouTubeTranscriptOptions = {
  language?: string;
  includeTimestamps?: boolean;
};

export type YouTubeCommentSortBy = "top_comments" | "new_comments";

export type YouTubeCommentQuery =
  | {
      video: YouTubeVideoInput;
      sortBy?: YouTubeCommentSortBy;
      pageToken?: never;
      maxResults?: number;
    }
  | {
      pageToken: string;
      video?: never;
      sortBy?: never;
      maxResults?: number;
    };

export type YouTubeCommentThread = {
  threadId: string;
  text: string;
  authorName?: string;
  likeCount?: string;
  replyCount?: string;
  isPinned: boolean;
  publishedText?: string;
};

export type YouTubeCommentPage = {
  kind: "comments";
  videoId: string;
  canonicalUrl: string;
  sortBy: YouTubeCommentSortBy;
  pageSize: number;
  nextPageToken?: string;
  threads: YouTubeCommentThread[];
};

export type YouTubeService = {
  parseInput: (input: string) => YouTubeLookupReference;
  getVideo: (input: YouTubeVideoInput) => Promise<YouTubeVideoRecord>;
  getPlaylist: (
    input: YouTubePlaylistInput | YouTubePlaylistQuery
  ) => Promise<YouTubePlaylistRecord>;
  getChannel: (input: YouTubeChannelInput) => Promise<YouTubeChannelRecord>;
  searchVideos: (query: YouTubeSearchQuery) => Promise<YouTubeSearchPage>;
  getTranscript: (
    input: YouTubeVideoInput,
    options?: YouTubeTranscriptOptions
  ) => Promise<YouTubeTranscriptRecord>;
  getComments: (query: YouTubeCommentQuery) => Promise<YouTubeCommentPage>;
};
