import { describe, expect, it, vi } from "vitest";

import { NotAvailableError } from "../../src/lib/mcp-errors.js";
import { type YouTubeTranscriptRecord } from "../../src/youtube/contracts.js";
import { createYouTubeService } from "../../src/youtube/service.js";
import { normalizeTranscriptRecord } from "../../src/youtube/normalize.js";
import { parseYouTubeInput } from "../../src/youtube/parser.js";
import type { YouTubeVideoReference } from "../../src/youtube/reference.js";

function expectVideoReference(value: ReturnType<typeof parseYouTubeInput>): YouTubeVideoReference {
  expect(value.kind).toBe("video");

  if (value.kind !== "video") {
    throw new Error("Expected a video reference");
  }

  return value;
}

function createSilentLogger() {
  return {
    debug: vi.fn(),
    info: vi.fn(),
    warn: vi.fn(),
    error: vi.fn()
  };
}

describe("youtube transcript normalization", () => {
  it("normalizes transcript segments and language metadata into a stable plain record", () => {
    const reference = expectVideoReference(
      parseYouTubeInput("https://www.youtube.com/watch?v=dQw4w9WgXcQ")
    );

    const record = normalizeTranscriptRecord(
      {
        languages: ["English", "Deutsch"],
        selectedLanguage: "English",
        transcript: {
          content: {
            body: {
              initial_segments: [
                {
                  start_ms: "0",
                  end_ms: "2200",
                  start_time_text: { text: "0:00" },
                  snippet: { text: "Hello world" }
                },
                {
                  start_ms: "2200",
                  end_ms: "4800",
                  start_time_text: { text: "0:02" },
                  snippet: { runs: [{ text: "Build " }, { text: "with MCP" }] }
                }
              ]
            }
          }
        }
      },
      reference,
      {
        basic_info: {
          title: "Transcript-ready video",
          channel: {
            name: "Example Dev"
          }
        },
        captions: {
          caption_tracks: [
            {
              name: { text: "English" },
              language_code: "en",
              kind: "asr",
              is_translatable: true
            },
            {
              name: { text: "Deutsch" },
              language_code: "de",
              is_translatable: true
            }
          ]
        }
      }
    );

    expect(record satisfies YouTubeTranscriptRecord).toBe(record);
    expect(record).toEqual({
      kind: "transcript",
      videoId: "dQw4w9WgXcQ",
      canonicalUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
      source: "watch",
      title: "Transcript-ready video",
      channelTitle: "Example Dev",
      language: "English",
      languages: [
        {
          label: "English",
          languageCode: "en",
          isSelected: true,
          isAutoGenerated: true,
          isTranslatable: true
        },
        {
          label: "Deutsch",
          languageCode: "de",
          isSelected: false,
          isTranslatable: true
        }
      ],
      segmentCount: 2,
      segments: [
        {
          startMs: 0,
          endMs: 2200,
          startTimeSeconds: 0,
          endTimeSeconds: 2,
          startTimeText: "0:00",
          text: "Hello world"
        },
        {
          startMs: 2200,
          endMs: 4800,
          startTimeSeconds: 2,
          endTimeSeconds: 4,
          startTimeText: "0:02",
          text: "Build with MCP"
        }
      ],
      text: "Hello world\nBuild with MCP"
    });
  });

  it("drops malformed transcript rows and still exposes translation language metadata", () => {
    const reference = expectVideoReference(parseYouTubeInput("dQw4w9WgXcQ"));

    const record = normalizeTranscriptRecord(
      {
        languages: ["English", "Español"],
        selectedLanguage: "Español",
        transcript: {
          content: {
            body: {
              initial_segments: [
                {
                  title: "Section header"
                },
                {
                  start_ms: "5000",
                  end_ms: "8100",
                  start_time_text: { simpleText: "0:05" },
                  snippet: { simpleText: "Hola mundo" }
                }
              ]
            }
          }
        }
      },
      reference,
      {
        captions: {
          translation_languages: [
            {
              language_code: "es",
              language_name: { text: "Español" }
            }
          ]
        }
      }
    );

    expect(record.languages).toEqual([
      {
        label: "English",
        isSelected: false
      },
      {
        label: "Español",
        languageCode: "es",
        isSelected: true,
        isTranslatable: true
      }
    ]);
    expect(record.segmentCount).toBe(1);
    expect(record.segments).toEqual([
      {
        startMs: 5000,
        endMs: 8100,
        startTimeSeconds: 5,
        endTimeSeconds: 8,
        startTimeText: "0:05",
        text: "Hola mundo"
      }
    ]);
    expect(record.text).toBe("Hola mundo");
  });
});

describe("youtube transcript service", () => {
  it("retrieves public transcripts from rich video info for urls and bare ids", async () => {
    const mediaInfo = {
      basic_info: {
        title: "Build an MCP Server",
        channel: {
          name: "Example Dev"
        }
      },
      captions: {
        caption_tracks: [
          {
            name: { text: "English" },
            language_code: "en",
            kind: "asr",
            is_translatable: true
          }
        ]
      },
      getTranscript: vi.fn().mockResolvedValue({
        languages: ["English"],
        selectedLanguage: "English",
        transcript: {
          content: {
            body: {
              initial_segments: [
                {
                  start_ms: "0",
                  end_ms: "1200",
                  start_time_text: { text: "0:00" },
                  snippet: { text: "Hello world" }
                }
              ]
            }
          }
        }
      })
    };
    const upstream = {
      getInfo: vi.fn().mockResolvedValue(mediaInfo),
      getBasicInfo: vi.fn(),
      getPlaylist: vi.fn(),
      getChannel: vi.fn()
    };
    const service = createYouTubeService({
      client: {
        getClient: vi.fn().mockResolvedValue(upstream),
        getConfig: vi.fn().mockReturnValue({}),
        reset: vi.fn()
      },
      logger: createSilentLogger()
    });

    await expect(
      service.getTranscript("https://www.youtube.com/watch?v=dQw4w9WgXcQ")
    ).resolves.toMatchObject({
      kind: "transcript",
      videoId: "dQw4w9WgXcQ",
      canonicalUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
      source: "watch",
      title: "Build an MCP Server",
      channelTitle: "Example Dev",
      language: "English",
      segmentCount: 1,
      text: "Hello world"
    });
    await expect(service.getTranscript("dQw4w9WgXcQ")).resolves.toMatchObject({
      kind: "transcript",
      videoId: "dQw4w9WgXcQ",
      source: "id",
      language: "English"
    });

    expect(upstream.getInfo).toHaveBeenCalledTimes(2);
    expect(mediaInfo.getTranscript).toHaveBeenCalledTimes(2);
    expect(upstream.getBasicInfo).not.toHaveBeenCalled();
  });

  it("selects an alternate transcript language by label or language code", async () => {
    const germanTranscript = {
      languages: ["English", "Deutsch"],
      selectedLanguage: "Deutsch",
      transcript: {
        content: {
          body: {
            initial_segments: [
              {
                start_ms: "0",
                end_ms: "2000",
                start_time_text: { text: "0:00" },
                snippet: { text: "Hallo Welt" }
              }
            ]
          }
        }
      }
    };
    const englishTranscript = {
      languages: ["English", "Deutsch"],
      selectedLanguage: "English",
      transcript: {
        content: {
          body: {
            initial_segments: [
              {
                start_ms: "0",
                end_ms: "1500",
                start_time_text: { text: "0:00" },
                snippet: { text: "Hello world" }
              }
            ]
          }
        }
      },
      selectLanguage: vi.fn().mockImplementation(async language => {
        expect(language).toBe("Deutsch");
        return germanTranscript;
      })
    };
    const upstream = {
      getInfo: vi.fn().mockResolvedValue({
        basic_info: {
          title: "Language-aware video"
        },
        captions: {
          caption_tracks: [
            {
              name: { text: "English" },
              language_code: "en",
              is_translatable: true
            },
            {
              name: { text: "Deutsch" },
              language_code: "de",
              is_translatable: true
            }
          ]
        },
        getTranscript: vi.fn().mockResolvedValue(englishTranscript)
      }),
      getBasicInfo: vi.fn(),
      getPlaylist: vi.fn(),
      getChannel: vi.fn()
    };
    const service = createYouTubeService({
      client: {
        getClient: vi.fn().mockResolvedValue(upstream),
        getConfig: vi.fn().mockReturnValue({}),
        reset: vi.fn()
      },
      logger: createSilentLogger()
    });

    await expect(
      service.getTranscript("dQw4w9WgXcQ", { language: "de" })
    ).resolves.toMatchObject({
      language: "Deutsch",
      text: "Hallo Welt"
    });

    expect(englishTranscript.selectLanguage).toHaveBeenCalledWith("Deutsch");
  });

  it("returns typed not-available failures for missing transcripts and missing languages", async () => {
    const service = createYouTubeService({
      client: {
        getClient: vi.fn().mockResolvedValue({
          getInfo: vi.fn().mockResolvedValue({
            captions: {
              caption_tracks: [
                {
                  name: { text: "English" },
                  language_code: "en"
                }
              ]
            },
            getTranscript: vi
              .fn()
              .mockRejectedValue(new Error("Transcript panel is unavailable"))
          }),
          getBasicInfo: vi.fn(),
          getPlaylist: vi.fn(),
          getChannel: vi.fn()
        }),
        getConfig: vi.fn().mockReturnValue({}),
        reset: vi.fn()
      },
      logger: createSilentLogger()
    });
    const languageService = createYouTubeService({
      client: {
        getClient: vi.fn().mockResolvedValue({
          getInfo: vi.fn().mockResolvedValue({
            captions: {
              caption_tracks: [
                {
                  name: { text: "English" },
                  language_code: "en"
                }
              ]
            },
            getTranscript: vi.fn().mockResolvedValue({
              languages: ["English"],
              selectedLanguage: "English",
              transcript: {
                content: {
                  body: {
                    initial_segments: [
                      {
                        start_ms: "0",
                        end_ms: "1200",
                        start_time_text: { text: "0:00" },
                        snippet: { text: "Hello world" }
                      }
                    ]
                  }
                }
              }
            })
          }),
          getBasicInfo: vi.fn(),
          getPlaylist: vi.fn(),
          getChannel: vi.fn()
        }),
        getConfig: vi.fn().mockReturnValue({}),
        reset: vi.fn()
      },
      logger: createSilentLogger()
    });

    await expect(service.getTranscript("dQw4w9WgXcQ")).rejects.toEqual(
      new NotAvailableError("No public transcript is available for this video.", {
        cause: "transcript_unavailable",
        details: {
          videoId: "dQw4w9WgXcQ"
        }
      })
    );
    await expect(
      languageService.getTranscript("dQw4w9WgXcQ", { language: "fr" })
    ).rejects.toEqual(
      new NotAvailableError(
        'Transcript language "fr" is not available for this video.',
        {
          cause: "transcript_language_unavailable",
          details: {
            videoId: "dQw4w9WgXcQ",
            language: "fr",
            availableLanguages: ["English"]
          }
        }
      )
    );
  });
});
