import { describe, expect, it, vi } from "vitest";

import {
  NotAvailableError,
  UpstreamUnavailableError
} from "../../src/lib/mcp-errors.js";
import { type YouTubeTranscriptRecord } from "../../src/youtube/contracts.js";
import { createYouTubeService } from "../../src/youtube/service.js";
import { createTranscriptFallbackAdapter } from "../../src/youtube/transcript-fallback.js";
import {
  formatTranscriptText,
  formatTranscriptTimestamp,
  normalizeTranscriptRecord
} from "../../src/youtube/normalize.js";
import { parseYouTubeInput } from "../../src/youtube/parser.js";
import type { YouTubeVideoReference } from "../../src/youtube/reference.js";
import * as rootModule from "../../src/index.js";
import * as youtubeModule from "../../src/youtube/index.js";

function expectVideoReference(value: ReturnType<typeof parseYouTubeInput>): YouTubeVideoReference {
  expect(value.kind).toBe("video");

  if (value.kind !== "video") {
    throw new Error("Expected a video reference");
  }

  return value;
}

function createSilentLogger() {
  return {
    debug: vi.fn(),
    info: vi.fn(),
    warn: vi.fn(),
    error: vi.fn()
  };
}

describe("youtube transcript normalization", () => {
  it("normalizes transcript segments and language metadata into a stable plain record", () => {
    const reference = expectVideoReference(
      parseYouTubeInput("https://www.youtube.com/watch?v=dQw4w9WgXcQ")
    );

    const record = normalizeTranscriptRecord(
      {
        languages: ["English", "Deutsch"],
        selectedLanguage: "English",
        transcript: {
          content: {
            body: {
              initial_segments: [
                {
                  start_ms: "0",
                  end_ms: "2200",
                  start_time_text: { text: "0:00" },
                  snippet: { text: "Hello world" }
                },
                {
                  start_ms: "2200",
                  end_ms: "4800",
                  start_time_text: { text: "0:02" },
                  snippet: { runs: [{ text: "Build " }, { text: "with MCP" }] }
                }
              ]
            }
          }
        }
      },
      reference,
      {
        basic_info: {
          title: "Transcript-ready video",
          channel: {
            name: "Example Dev"
          }
        },
        captions: {
          caption_tracks: [
            {
              name: { text: "English" },
              language_code: "en",
              kind: "asr",
              is_translatable: true
            },
            {
              name: { text: "Deutsch" },
              language_code: "de",
              is_translatable: true
            }
          ]
        }
      }
    );

    expect(record satisfies YouTubeTranscriptRecord).toBe(record);
    expect(record).toEqual({
      kind: "transcript",
      videoId: "dQw4w9WgXcQ",
      canonicalUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
      source: "watch",
      title: "Transcript-ready video",
      channelTitle: "Example Dev",
      language: "English",
      languages: [
        {
          label: "English",
          languageCode: "en",
          isSelected: true,
          isAutoGenerated: true,
          isTranslatable: true
        },
        {
          label: "Deutsch",
          languageCode: "de",
          isSelected: false,
          isTranslatable: true
        }
      ],
      includeTimestamps: false,
      retrievalMethod: "primary",
      segmentCount: 2,
      segments: [
        {
          startMs: 0,
          endMs: 2200,
          startTimeSeconds: 0,
          endTimeSeconds: 2,
          startTimeText: "0:00",
          text: "Hello world"
        },
        {
          startMs: 2200,
          endMs: 4800,
          startTimeSeconds: 2,
          endTimeSeconds: 4,
          startTimeText: "0:02",
          text: "Build with MCP"
        }
      ],
      text: "Hello world\nBuild with MCP"
    });
  });

  it("drops malformed transcript rows and still exposes translation language metadata", () => {
    const reference = expectVideoReference(parseYouTubeInput("dQw4w9WgXcQ"));

    const record = normalizeTranscriptRecord(
      {
        languages: ["English", "Español"],
        selectedLanguage: "Español",
        transcript: {
          content: {
            body: {
              initial_segments: [
                {
                  title: "Section header"
                },
                {
                  start_ms: "5000",
                  end_ms: "8100",
                  start_time_text: { simpleText: "0:05" },
                  snippet: { simpleText: "Hola mundo" }
                }
              ]
            }
          }
        }
      },
      reference,
      {
        captions: {
          translation_languages: [
            {
              language_code: "es",
              language_name: { text: "Español" }
            }
          ]
        }
      }
    );

    expect(record.languages).toEqual([
      {
        label: "English",
        isSelected: false
      },
      {
        label: "Español",
        languageCode: "es",
        isSelected: true,
        isTranslatable: true
      }
    ]);
    expect(record.segmentCount).toBe(1);
    expect(record.segments).toEqual([
      {
        startMs: 5000,
        endMs: 8100,
        startTimeSeconds: 5,
        endTimeSeconds: 8,
        startTimeText: "0:05",
        text: "Hola mundo"
      }
    ]);
    expect(record.text).toBe("Hola mundo");
  });

  it("formats timestamp-on and timestamp-off transcript text from the same segments", () => {
    const record = normalizeTranscriptRecord(
      {
        languages: ["English"],
        selectedLanguage: "English",
        transcript: {
          content: {
            body: {
              initial_segments: [
                {
                  start_ms: "0",
                  end_ms: "2100",
                  start_time_text: { text: "0:00" },
                  snippet: { text: "Hello world" }
                },
                {
                  start_ms: "2100",
                  end_ms: "4800",
                  start_time_text: { text: "0:02" },
                  snippet: { text: "Build with MCP" }
                }
              ]
            }
          }
        }
      },
      expectVideoReference(parseYouTubeInput("dQw4w9WgXcQ"))
    );

    expect(formatTranscriptText(record.segments)).toBe("Hello world\nBuild with MCP");
    expect(
      formatTranscriptText(record.segments, { includeTimestamps: true })
    ).toBe("0:00 Hello world\n0:02 Build with MCP");
    expect(
      normalizeTranscriptRecord(
        {
          languages: ["English"],
          selectedLanguage: "English",
          transcript: {
            content: {
              body: {
                initial_segments: [
                  {
                    start_ms: "0",
                    end_ms: "2100",
                    start_time_text: { text: "0:00" },
                    snippet: { text: "Hello world" }
                  }
                ]
              }
            }
          }
        },
        expectVideoReference(parseYouTubeInput("dQw4w9WgXcQ")),
        undefined,
        { includeTimestamps: true }
      ).text
    ).toBe("0:00 Hello world");
  });
});

describe("youtube transcript exports and edge cases", () => {
  it("re-exports the transcript helpers through the youtube module and package root", () => {
    expect(youtubeModule.normalizeTranscriptRecord).toBe(normalizeTranscriptRecord);
    expect(youtubeModule.formatTranscriptText).toBe(formatTranscriptText);
    expect(youtubeModule.formatTranscriptTimestamp).toBe(formatTranscriptTimestamp);
    expect(youtubeModule.createTranscriptFallbackAdapter).toBeDefined();
    expect(rootModule.normalizeTranscriptRecord).toBe(normalizeTranscriptRecord);
    expect(rootModule.formatTranscriptText).toBe(formatTranscriptText);
    expect(rootModule.createTranscriptFallbackAdapter).toBeDefined();
  });

  it("keeps long-form transcript timestamps stable across hour boundaries", () => {
    const record = normalizeTranscriptRecord(
      {
        languages: ["English"],
        selectedLanguage: "English",
        transcript: {
          content: {
            body: {
              initial_segments: [
                {
                  start_ms: "3661000",
                  end_ms: "3665000",
                  start_time_text: { text: "1:01:01" },
                  snippet: { text: "Hour-mark transcript segment" }
                }
              ]
            }
          }
        }
      },
      expectVideoReference(parseYouTubeInput("dQw4w9WgXcQ")),
      undefined,
      { includeTimestamps: true }
    );

    expect(formatTranscriptTimestamp(3661)).toBe("1:01:01");
    expect(record.text).toBe("1:01:01 Hour-mark transcript segment");
    expect(record.segmentCount).toBe(1);
  });
});

describe("youtube transcript service", () => {
  it("retrieves public transcripts from rich video info for urls and bare ids", async () => {
    const mediaInfo = {
      basic_info: {
        title: "Build an MCP Server",
        channel: {
          name: "Example Dev"
        }
      },
      captions: {
        caption_tracks: [
          {
            name: { text: "English" },
            language_code: "en",
            kind: "asr",
            is_translatable: true
          }
        ]
      },
      getTranscript: vi.fn().mockResolvedValue({
        languages: ["English"],
        selectedLanguage: "English",
        transcript: {
          content: {
            body: {
              initial_segments: [
                {
                  start_ms: "0",
                  end_ms: "1200",
                  start_time_text: { text: "0:00" },
                  snippet: { text: "Hello world" }
                }
              ]
            }
          }
        }
      })
    };
    const upstream = {
      getInfo: vi.fn().mockResolvedValue(mediaInfo),
      getBasicInfo: vi.fn(),
      getPlaylist: vi.fn(),
      getChannel: vi.fn()
    };
    const service = createYouTubeService({
      client: {
        getClient: vi.fn().mockResolvedValue(upstream),
        getConfig: vi.fn().mockReturnValue({}),
        reset: vi.fn()
      },
      logger: createSilentLogger()
    });

    await expect(
      service.getTranscript("https://www.youtube.com/watch?v=dQw4w9WgXcQ")
    ).resolves.toMatchObject({
      kind: "transcript",
      videoId: "dQw4w9WgXcQ",
      canonicalUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
      source: "watch",
      title: "Build an MCP Server",
      channelTitle: "Example Dev",
      language: "English",
      includeTimestamps: false,
      retrievalMethod: "primary",
      segmentCount: 1,
      text: "Hello world"
    });
    await expect(service.getTranscript("dQw4w9WgXcQ")).resolves.toMatchObject({
      kind: "transcript",
      videoId: "dQw4w9WgXcQ",
      source: "id",
      language: "English"
    });

    expect(upstream.getInfo).toHaveBeenCalledTimes(2);
    expect(mediaInfo.getTranscript).toHaveBeenCalledTimes(2);
    expect(upstream.getBasicInfo).not.toHaveBeenCalled();
  });

  it("selects an alternate transcript language by label or language code", async () => {
    const germanTranscript = {
      languages: ["English", "Deutsch"],
      selectedLanguage: "Deutsch",
      transcript: {
        content: {
          body: {
            initial_segments: [
              {
                start_ms: "0",
                end_ms: "2000",
                start_time_text: { text: "0:00" },
                snippet: { text: "Hallo Welt" }
              }
            ]
          }
        }
      }
    };
    const englishTranscript = {
      languages: ["English", "Deutsch"],
      selectedLanguage: "English",
      transcript: {
        content: {
          body: {
            initial_segments: [
              {
                start_ms: "0",
                end_ms: "1500",
                start_time_text: { text: "0:00" },
                snippet: { text: "Hello world" }
              }
            ]
          }
        }
      },
      selectLanguage: vi.fn().mockImplementation(async language => {
        expect(language).toBe("Deutsch");
        return germanTranscript;
      })
    };
    const upstream = {
      getInfo: vi.fn().mockResolvedValue({
        basic_info: {
          title: "Language-aware video"
        },
        captions: {
          caption_tracks: [
            {
              name: { text: "English" },
              language_code: "en",
              is_translatable: true
            },
            {
              name: { text: "Deutsch" },
              language_code: "de",
              is_translatable: true
            }
          ]
        },
        getTranscript: vi.fn().mockResolvedValue(englishTranscript)
      }),
      getBasicInfo: vi.fn(),
      getPlaylist: vi.fn(),
      getChannel: vi.fn()
    };
    const service = createYouTubeService({
      client: {
        getClient: vi.fn().mockResolvedValue(upstream),
        getConfig: vi.fn().mockReturnValue({}),
        reset: vi.fn()
      },
      logger: createSilentLogger()
    });

    await expect(
      service.getTranscript("dQw4w9WgXcQ", { language: "de" })
    ).resolves.toMatchObject({
      language: "Deutsch",
      includeTimestamps: false,
      retrievalMethod: "primary",
      text: "Hallo Welt"
    });

    expect(englishTranscript.selectLanguage).toHaveBeenCalledWith("Deutsch");
  });

  it("falls back to the secondary extractor and keeps timestamp formatting stable", async () => {
    const transcriptFallback = {
      getTranscript: vi.fn().mockResolvedValue({
        languageCode: "de",
        languageLabel: "Deutsch",
        segments: [
          {
            startMs: 0,
            endMs: 2000,
            startTimeSeconds: 0,
            endTimeSeconds: 2,
            startTimeText: "0:00",
            text: "Hallo Welt"
          }
        ]
      })
    };
    const service = createYouTubeService({
      client: {
        getClient: vi.fn().mockResolvedValue({
          getInfo: vi.fn().mockResolvedValue({
            basic_info: {
              title: "Fallback video"
            },
            captions: {
              caption_tracks: [
                {
                  name: { text: "English" },
                  language_code: "en"
                },
                {
                  name: { text: "Deutsch" },
                  language_code: "de"
                }
              ]
            },
            getTranscript: vi.fn().mockRejectedValue(
              new UpstreamUnavailableError(
                "Primary transcript lookup is temporarily unavailable."
              )
            )
          }),
          getBasicInfo: vi.fn(),
          getPlaylist: vi.fn(),
          getChannel: vi.fn()
        }),
        getConfig: vi.fn().mockReturnValue({}),
        reset: vi.fn()
      },
      logger: createSilentLogger(),
      transcriptFallback
    });

    await expect(
      service.getTranscript("dQw4w9WgXcQ", {
        language: "de",
        includeTimestamps: true
      })
    ).resolves.toMatchObject({
      language: "Deutsch",
      includeTimestamps: true,
      retrievalMethod: "fallback",
      text: "0:00 Hallo Welt"
    });

    expect(transcriptFallback.getTranscript).toHaveBeenCalledWith({
      videoId: "dQw4w9WgXcQ",
      languageCode: "de",
      languageLabel: "Deutsch"
    });
  });

  it("returns typed not-available failures for missing transcripts and missing languages", async () => {
    const transcriptFallback = {
      getTranscript: vi.fn().mockRejectedValue(
        new NotAvailableError("No public transcript is available for this video.", {
          cause: "transcript_unavailable",
          details: {
            videoId: "dQw4w9WgXcQ",
            fallback: true
          }
        })
      )
    };
    const service = createYouTubeService({
      client: {
        getClient: vi.fn().mockResolvedValue({
          getInfo: vi.fn().mockResolvedValue({
            captions: {
              caption_tracks: [
                {
                  name: { text: "English" },
                  language_code: "en"
                }
              ]
            },
            getTranscript: vi
              .fn()
              .mockRejectedValue(new Error("Transcript panel is unavailable"))
          }),
          getBasicInfo: vi.fn(),
          getPlaylist: vi.fn(),
          getChannel: vi.fn()
        }),
        getConfig: vi.fn().mockReturnValue({}),
        reset: vi.fn()
      },
      logger: createSilentLogger(),
      transcriptFallback
    });
    const languageService = createYouTubeService({
      client: {
        getClient: vi.fn().mockResolvedValue({
          getInfo: vi.fn().mockResolvedValue({
            captions: {
              caption_tracks: [
                {
                  name: { text: "English" },
                  language_code: "en"
                }
              ]
            },
            getTranscript: vi.fn().mockResolvedValue({
              languages: ["English"],
              selectedLanguage: "English",
              transcript: {
                content: {
                  body: {
                    initial_segments: [
                      {
                        start_ms: "0",
                        end_ms: "1200",
                        start_time_text: { text: "0:00" },
                        snippet: { text: "Hello world" }
                      }
                    ]
                  }
                }
              }
            })
          }),
          getBasicInfo: vi.fn(),
          getPlaylist: vi.fn(),
          getChannel: vi.fn()
        }),
        getConfig: vi.fn().mockReturnValue({}),
        reset: vi.fn()
      },
      logger: createSilentLogger(),
      transcriptFallback
    });

    await expect(service.getTranscript("dQw4w9WgXcQ")).rejects.toEqual(
      new NotAvailableError("No public transcript is available for this video.", {
        cause: "transcript_unavailable",
        details: {
          videoId: "dQw4w9WgXcQ",
          fallback: true
        }
      })
    );
    await expect(
      languageService.getTranscript("dQw4w9WgXcQ", { language: "fr" })
    ).rejects.toEqual(
      new NotAvailableError(
        'Transcript language "fr" is not available for this video.',
        {
          cause: "transcript_language_unavailable",
          details: {
            videoId: "dQw4w9WgXcQ",
            language: "fr",
            availableLanguages: ["English"]
          }
        }
      )
    );
    expect(transcriptFallback.getTranscript).toHaveBeenCalledTimes(1);
  });

  it("recovers via the fallback when getTranscript throws an HTTP 400-style error even though caption tracks are present", async () => {
    // Regression case: youtubei.js getTranscript() hits /youtubei/v1/get_transcript and
    // gets HTTP 400 even when getInfo() returns caption tracks for the video.
    // The service must fall through to the fallback adapter in this case.
    const http400Error = new Error("Status code: 400");
    const transcriptFallback = {
      getTranscript: vi.fn().mockResolvedValue({
        languageCode: "en",
        languageLabel: "English",
        segments: [
          {
            startMs: 0,
            endMs: 3000,
            startTimeSeconds: 0,
            endTimeSeconds: 3,
            startTimeText: "0:00",
            text: "Hello from the fallback path"
          }
        ]
      })
    };
    const service = createYouTubeService({
      client: {
        getClient: vi.fn().mockResolvedValue({
          getInfo: vi.fn().mockResolvedValue({
            basic_info: {
              title: "Caption-bearing video",
              channel: { name: "Test Channel" }
            },
            captions: {
              caption_tracks: [
                {
                  name: { text: "English" },
                  language_code: "en",
                  kind: "asr",
                  is_translatable: true
                }
              ]
            },
            getTranscript: vi.fn().mockRejectedValue(http400Error)
          }),
          getBasicInfo: vi.fn(),
          getPlaylist: vi.fn(),
          getChannel: vi.fn()
        }),
        getConfig: vi.fn().mockReturnValue({}),
        reset: vi.fn()
      },
      logger: createSilentLogger(),
      transcriptFallback
    });

    await expect(
      service.getTranscript("aircAruvnKk")
    ).resolves.toMatchObject({
      kind: "transcript",
      videoId: "aircAruvnKk",
      retrievalMethod: "fallback",
      language: "English",
      text: "Hello from the fallback path"
    });

    expect(transcriptFallback.getTranscript).toHaveBeenCalledTimes(1);
  });

  it("returns transcript_unavailable when getTranscript fails and the fallback also returns no segments", async () => {
    // True missing-transcript case: both primary and fallback fail to retrieve content.
    const transcriptFallback = {
      getTranscript: vi.fn().mockRejectedValue(
        new NotAvailableError("No public transcript is available for this video.", {
          cause: "transcript_unavailable",
          details: { videoId: "dQw4w9WgXcQ", fallback: true }
        })
      )
    };
    const service = createYouTubeService({
      client: {
        getClient: vi.fn().mockResolvedValue({
          getInfo: vi.fn().mockResolvedValue({
            basic_info: { title: "No-transcript video" },
            captions: {
              caption_tracks: []
            },
            getTranscript: vi.fn().mockRejectedValue(
              new Error("Transcript panel is unavailable")
            )
          }),
          getBasicInfo: vi.fn(),
          getPlaylist: vi.fn(),
          getChannel: vi.fn()
        }),
        getConfig: vi.fn().mockReturnValue({}),
        reset: vi.fn()
      },
      logger: createSilentLogger(),
      transcriptFallback
    });

    const rejection = await service.getTranscript("dQw4w9WgXcQ").catch(e => e);
    expect(rejection).toBeInstanceOf(NotAvailableError);
    expect(rejection.causeDetail).toBe("transcript_unavailable");
  });
});

describe("InnerTube player-based transcript fallback adapter", () => {
  it("fetches caption tracks from the InnerTube player endpoint and parses timedtext json3", async () => {
    const playerResponse = {
      captions: {
        playerCaptionsTracklistRenderer: {
          captionTracks: [
            {
              baseUrl: "https://www.youtube.com/api/timedtext?v=aircAruvnKk&lang=en",
              languageCode: "en",
              name: { simpleText: "English" }
            }
          ]
        }
      }
    };
    const timedTextResponse = {
      events: [
        { tStartMs: 0, dDurationMs: 3000, segs: [{ utf8: "Hello " }, { utf8: "world" }] },
        { tStartMs: 3000, dDurationMs: 2000, segs: [{ utf8: "MCP transcript" }] },
        // Events without segs (music annotations) should be skipped
        { tStartMs: 5000, dDurationMs: 1000 }
      ]
    };

    const fetchFn = vi.fn()
      .mockResolvedValueOnce({
        ok: true,
        json: async () => playerResponse
      })
      .mockResolvedValueOnce({
        ok: true,
        json: async () => timedTextResponse
      });

    const adapter = createTranscriptFallbackAdapter({ fetch: fetchFn });
    const result = await adapter.getTranscript({ videoId: "aircAruvnKk" });

    expect(result.languageCode).toBe("en");
    expect(result.languageLabel).toBe("English");
    expect(result.segments).toHaveLength(2);
    expect(result.segments[0]).toMatchObject({
      startMs: 0,
      endMs: 3000,
      startTimeSeconds: 0,
      endTimeSeconds: 3,
      startTimeText: "0:00",
      text: "Hello world"
    });
    expect(result.segments[1]).toMatchObject({
      startMs: 3000,
      endMs: 5000,
      startTimeSeconds: 3,
      text: "MCP transcript"
    });

    // Verify InnerTube Android client context is used
    const [playerUrl, playerInit] = fetchFn.mock.calls[0];
    expect(playerUrl).toBe("https://www.youtube.com/youtubei/v1/player");
    expect(JSON.parse(playerInit.body)).toMatchObject({
      videoId: "aircAruvnKk",
      context: { client: { clientName: "ANDROID" } }
    });

    // Verify timedtext URL has json3 format
    const timedTextUrl = fetchFn.mock.calls[1][0];
    expect(timedTextUrl).toContain("fmt=json3");
  });

  it("selects the requested language track when multiple caption tracks are available", async () => {
    const playerResponse = {
      captions: {
        playerCaptionsTracklistRenderer: {
          captionTracks: [
            {
              baseUrl: "https://www.youtube.com/api/timedtext?v=testId&lang=en",
              languageCode: "en",
              name: { simpleText: "English" }
            },
            {
              baseUrl: "https://www.youtube.com/api/timedtext?v=testId&lang=de",
              languageCode: "de",
              name: { simpleText: "Deutsch" }
            }
          ]
        }
      }
    };
    const timedTextResponse = {
      events: [
        { tStartMs: 0, dDurationMs: 2000, segs: [{ utf8: "Hallo Welt" }] }
      ]
    };

    const fetchFn = vi.fn()
      .mockResolvedValueOnce({ ok: true, json: async () => playerResponse })
      .mockResolvedValueOnce({ ok: true, json: async () => timedTextResponse });

    const adapter = createTranscriptFallbackAdapter({ fetch: fetchFn });
    const result = await adapter.getTranscript({
      videoId: "testId",
      languageCode: "de"
    });

    expect(result.languageCode).toBe("de");
    expect(result.languageLabel).toBe("Deutsch");
    expect(result.segments[0].text).toBe("Hallo Welt");

    // Verify the German track URL was used
    const timedTextUrl = fetchFn.mock.calls[1][0];
    expect(timedTextUrl).toContain("lang=de");
  });

  it("returns transcript_unavailable when the player response contains no caption tracks", async () => {
    const playerResponse = {
      captions: {
        playerCaptionsTracklistRenderer: {
          captionTracks: []
        }
      }
    };

    const fetchFn = vi.fn().mockResolvedValueOnce({
      ok: true,
      json: async () => playerResponse
    });

    const adapter = createTranscriptFallbackAdapter({ fetch: fetchFn });

    const rejection = await adapter.getTranscript({ videoId: "noTrackVideo" }).catch(e => e);
    expect(rejection).toBeInstanceOf(NotAvailableError);
    expect(rejection.causeDetail).toBe("transcript_unavailable");
  });

  it("returns UpstreamUnavailableError when the player endpoint returns a non-200 status", async () => {
    const fetchFn = vi.fn().mockResolvedValueOnce({
      ok: false,
      status: 400
    });

    const adapter = createTranscriptFallbackAdapter({ fetch: fetchFn });

    await expect(
      adapter.getTranscript({ videoId: "aircAruvnKk" })
    ).rejects.toBeInstanceOf(UpstreamUnavailableError);
  });
});
